apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifest1
- manifest2
- manifest3 
- manifest4
- manifest5 
- manifest6 
- manifest7 
- manifets8 
- manifest9 
- manifest10


