apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix : layer3-

resources:
- layer31 
- layer32
- layer33
- layer34
- layer35
- layer36
- layer37
- layer38
- layer39 
- layer310 






